// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPI.Database;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
                            Index = 1,
                            Name = "Bulbasaur",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/1.png",
                            Type = "Grass/Poison"
                        },
                        new
                        {
                            Id = 2,
                            Description = "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
                            Index = 2,
                            Name = "Ivysaur",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/2.png",
                            Type = "Grass/Poison"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
                            Index = 3,
                            Name = "Venusaur",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/3.png",
                            Type = "Grass/Poison"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
                            Index = 4,
                            Name = "Charmander",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/4.png",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 5,
                            Description = "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
                            Index = 5,
                            Name = "Charmeleon",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/5.png",
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
                            Index = 6,
                            Name = "Charizard",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/6.png",
                            Type = "Fire/Flying"
                        },
                        new
                        {
                            Id = 7,
                            Description = "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
                            Index = 7,
                            Name = "Squirtle",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/7.png",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.",
                            Index = 8,
                            Name = "Wartortle",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/8.png",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Once it takes aim at its enemy, it blasts out water with even more force than a fire hose.",
                            Index = 9,
                            Name = "Blastoise",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/9.png",
                            Type = "Water"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
                            Index = 10,
                            Name = "Caterpie",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/10.png",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 11,
                            Description = "This is its pre-evolved form. At this stage, it can only harden, so it remains motionless to avoid attack.",
                            Index = 11,
                            Name = "Metapod",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/11.png",
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 12,
                            Description = "In battle, it flaps its wings at great speed to release highly toxic dust into the air.",
                            Index = 12,
                            Name = "Butterfree",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/12.png",
                            Type = "Bug/Flying"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Often found in forests and grasslands. It has a sharp, toxic barb of around two inches on top of its head.",
                            Index = 13,
                            Name = "Weedle",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/13.png",
                            Type = "Bug/Poison"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.",
                            Index = 14,
                            Name = "Kakuna",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/14.png",
                            Type = "Bug/Poison"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
                            Index = 15,
                            Name = "Beedrill",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/15.png",
                            Type = "Bug/Poison"
                        },
                        new
                        {
                            Id = 16,
                            Description = "It usually hides in tall grass. Because it dislikes fighting, it protects itself by kicking up sand.",
                            Index = 16,
                            Name = "Pidgey",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/16.png",
                            Type = "Normal/Flying"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.",
                            Index = 17,
                            Name = "Pidgeotto",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/17.png",
                            Type = "Normal/Flying"
                        },
                        new
                        {
                            Id = 18,
                            Description = "When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.",
                            Index = 18,
                            Name = "Pidgeot",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/18.png",
                            Type = "Normal/Flying"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
                            Index = 19,
                            Name = "Rattata",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/19.png",
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 20,
                            Description = "It uses its whiskers to maintain its balance. It apparently slows down if they are cut off.",
                            Index = 20,
                            Name = "Raticate",
                            SpriteUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/20.png",
                            Type = "Normal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
